version: '3.8'

services:
  api:
    build: ./backend
    container_name: rota_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - rota-network

  worker:
    build: ./backend
    container_name: rota_worker
    command: celery -A app.worker.celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - POSTGRES_SERVER=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - rota-network

  db:
    image: timescale/timescaledb:latest-pg14
    container_name: rota_db
    environment:
      - POSTGRES_USER=rota
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=rota_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rota-network

  redis:
    image: redis:alpine
    container_name: rota_redis
    ports:
      - "6379:6379"
    networks:
      - rota-network

volumes:
  postgres_data:


networks:
  rota-network:
    driver: bridge
